-
  branches:
    only:
      - release
  environment:
    NPM_TOKEN:
      secure: nqiPMrQUkUXSgsw0xgsEPIGVlgN5gAI2fhfvj8RHcLmcafuuFc+EEqYy11ah0Bna

  skip_branch_with_pr: true
  before_build:
    - npm install

  build_script:
    - npm run build
    - echo publish package
    - npm run ci-publish
-
  branches:
    only:
      - master
  before_build:
    - npm install

  build_script:
    - npm run build
